// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmoynjphklcbhajxvgdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtb3luanBoa2xjYmhhanh2Z2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDkzNTgsImV4cCI6MjA2NDEyNTM1OH0.mAeslZbh1FAS2ox0RKcsxXMeuxtczHEv8egsUg1ZoIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);